Repository Proyecto-Desarrollo-web-ISPC/Proyecto-Integrador-Modulo-FullStack_2023, pull requests merged in 2023-09, with the labels that each got.

#23 Cristian - Merge a rama developer
  Frontend/css/styles.css
  Frontend/img/logo-dark.png
  Frontend/img/logo-light.png
  Frontend/img/payments/American_Express-Logo.wine.svg
  Frontend/img/payments/Mastercard-Logo.wine.svg
  Frontend/img/payments/PayPal-Logo.wine.svg
  Frontend/img/payments/Visa_Inc.-Logo.wine.svg
  Frontend/img/products/Alemania/Alemania-1954-primera.svg
  Frontend/img/products/Alemania/Alemania-1954-segunda.svg
  Frontend/img/products/Alemania/Alemania-1974-primera.svg
  Frontend/img/products/Alemania/Alemania-1974-segunda.svg
  Frontend/img/products/Alemania/Alemania-2014-primera.svg
  Frontend/img/products/Alemania/Alemania-2014-segunda.svg
  Frontend/img/products/Argentina/Argentina-1978-primera.svg
  Frontend/img/products/Argentina/Argentina-1978-segunda.svg
  Frontend/img/products/Argentina/Argentina-1978-tercera.svg
  Frontend/img/products/Argentina/Argentina-1986-primera.svg
  Frontend/img/products/Argentina/Argentina-1986-segunda.svg
  Frontend/img/products/Argentina/Argentina-2002-primera.svg
  Frontend/img/products/Argentina/Argentina-2002-segunda.svg
  Frontend/img/products/Brasil/Brasil-1958-primera.svg
  Frontend/img/products/Brasil/Brasil-1962-primera.svg
  Frontend/img/products/Brasil/Brasil-1970-primera.svg
  Frontend/img/products/Brasil/Brasil-1970-segunda.svg
  Frontend/img/products/Brasil/Brasil-1994-primera.svg
  Frontend/img/products/Brasil/Brasil-1994-segunda.svg
  Frontend/img/products/Brasil/Brasil-2002-primera.svg
  Frontend/img/products/Brasil/Brasil-2002-segunda.svg
  Frontend/pages/about.html
  Frontend/pages/cart.html
  Frontend/pages/index.html
  Frontend/pages/products.html
  Frontend/src/themeModeAbout.js
  Frontend/src/themeModeCart.js
  Frontend/src/themeModeIndex.js
  Frontend/src/themeModeProducts.js
Labels: enhancement

#24 Elimino archivos subidos por accidente
  Frontend/pages/about.html
  Frontend/pages/index.html
Labels: wontfix

#33 Estructura modular .js y revinculación en archivos .html
  Frontend/pages/cart.html
  Frontend/pages/products.html
  Frontend/src/main.js
  Frontend/src/themeModeAbout.js
  Frontend/src/themeModeCart.js
  Frontend/src/themeModeProducts.js
  Frontend/src/themeModeToggler.js
Labels: Improvement

#35 Victoria
  Frontend/css/styles.css
  Frontend/img/products/Argentina/Argentina-2022-primera.svg
  Frontend/img/products/gral/28985.jpeg
  Frontend/img/products/gral/CAMPEONES-DE-LOS-MUNDIALES.jpg
  Frontend/img/products/gral/argcamp.jpg
  Frontend/img/products/gral/balones.jpg
  Frontend/img/products/gral/camisetas.jpg
  Frontend/img/products/gral/campeones-en-octavos-1920-10.jpg
  Frontend/img/products/gral/copa30.jpg
  Frontend/img/products/gral/every-world-cup-ball-from-beginning-to-today.jpg
  Frontend/img/products/gral/mundiales.jpg
  Frontend/img/products/gral/pelotas.jpg
  Frontend/pages/index.html
  Frontend/src/popup.js
  README.md
Labels: Improvement

#40 Victoria
  Frontend/css/styles.css
  Frontend/img/products/Argentina/Argentina-2022-segunda.svg
  Frontend/pages/index.html
  README.md
Labels: Improvement

#43 Cristian
  Frontend/img/copa-del-mundo.png
  Frontend/img/products/Argentina/Argentina-2002-primera.svg
  Frontend/img/products/Argentina/Argentina-2002-segunda.svg
  Frontend/pages/cart.html
  Frontend/pages/index.html
  Frontend/pages/products.html
  Frontend/src/themeModeToggler.js
Labels: Improvement

#44 Pablo
  Frontend/css/styles.css
  Frontend/pages/about.html
Labels: enhancement

#46 Cristian
  Frontend/img/products/España/2010 seleccion española primera - 2.svg
  Frontend/img/products/España/España-2010-primera.svg
  Frontend/img/products/España/España-2010-segunda.svg
  Frontend/img/products/Francia/Francia-1998-primera.svg
  Frontend/img/products/Francia/Francia-1998-segunda.svg
  Frontend/img/products/Inglaterra/Inglaterra-1966-Segunda.svg
  Frontend/img/products/Inglaterra/Inglaterra-1968-Primera.svg
  Frontend/img/products/Italia/Italia-1934-Primera.svg
  Frontend/img/products/Italia/Italia-1938-Segunda.svg
  Frontend/img/products/Italia/Italia-1982-Primera.svg
  Frontend/img/products/Italia/Italia-1982-Segunda.svg
  Frontend/img/products/Italia/Italia-2006-Primera.svg
  Frontend/img/products/Italia/Italia-2006-Segunda.svg
  Frontend/img/products/Uruguay/Uruguay-1930-Primera.svg
  Frontend/img/products/Uruguay/Uruguay-1950-Primera.svg
  Frontend/pages/about.html
  Frontend/pages/cart.html
  Frontend/pages/index.html
  Frontend/pages/products.html
Labels: Improvement

#47 Corrijo código para pasar validaciones de W3C
  Frontend/pages/about.html
  Frontend/pages/products.html
Labels: Improvement

#49 Corrijo imagen Argentina y la ruta de imagen. Corrijo reglas css y Titulo de secciones de productos.
  Frontend/css/styles.css
  Frontend/img/products/Background_img/Argentina.svg
  Frontend/pages/products.html
Labels: Improvement

#48 Aplico diseño responsive en index.html y about.html
  Frontend/pages/about.html
  Frontend/pages/index.html
Labels: enhancement

#50 Cristian
  Frontend/pages/about.html
  Frontend/pages/cart.html
  Frontend/pages/index.html
  Frontend/pages/products.html
  Frontend/src/themeModeToggler.js
Labels: Improvement

#53 Corrijo sección de productos de Argentina
  Frontend/img/products/Argentina/Argentina-2002-primera.svg
  Frontend/img/products/Argentina/Argentina-2002-segunda.svg
  Frontend/img/products/Argentina/Argentina-2021-Primera.svg
  Frontend/pages/products.html
Labels: Improvement

#55 Corrijo path de imagen
  Frontend/pages/index.html
Labels: Improvement

#58 Developer
  Backend/src/Enums/Estado.py
  Backend/src/Enums/Rol_enum.py
  Backend/src/Enums/__pycache__/Rol_enum.cpython-311.pyc
  Frontend/img/logo-dark.png
  Frontend/img/logo-light.png
  Frontend/img/payments/American_Express-Logo.wine.svg
  Frontend/img/payments/Mastercard-Logo.wine.svg
  Frontend/img/payments/PayPal-Logo.wine.svg
  Frontend/img/payments/Visa_Inc.-Logo.wine.svg
  Frontend/img/products/Alemania/Alemania-1954-primera.svg
  Frontend/img/products/Alemania/Alemania-1954-segunda.svg
  Frontend/img/products/Alemania/Alemania-1974-primera.svg
  Frontend/img/products/Alemania/Alemania-1974-segunda.svg
  Frontend/img/products/Alemania/Alemania-2014-primera.svg
  Frontend/img/products/Alemania/Alemania-2014-segunda.svg
  Frontend/img/products/Argentina/Argentina-1978-primera.svg
  Frontend/img/products/Argentina/Argentina-1978-segunda.svg
  Frontend/img/products/Argentina/Argentina-1978-tercera.svg
  Frontend/img/products/Argentina/Argentina-1986-primera.svg
  Frontend/img/products/Argentina/Argentina-1986-segunda.svg
  Frontend/img/products/Brasil/Brasil-1958-primera.svg
  Frontend/img/products/Brasil/Brasil-1962-primera.svg
  Frontend/img/products/Brasil/Brasil-1970-primera.svg
  Frontend/img/products/Brasil/Brasil-1970-segunda.svg
  Frontend/img/products/Brasil/Brasil-1994-primera.svg
  Frontend/img/products/Brasil/Brasil-1994-segunda.svg
  Frontend/img/products/Brasil/Brasil-2002-primera.svg
  Frontend/img/products/Brasil/Brasil-2002-segunda.svg
  Frontend/pages/about.html
  Frontend/pages/cart.html
  Frontend/pages/index.html
  Frontend/pages/products.html
  Frontend/src/main.js
  Frontend/src/themeModeToggler.js
Labels: documentation
