Repository Proyecto-Desarrollo-web-ISPC/Proyecto-Integrador-Modulo-FullStack_2023, pull requests merged in 2023-10, with the labels that each got.

#62 Pablo - Agrega estructura para funcionalidad de login
  Frontend/pages/index.html
Labels: enhancement

#64 Victoria - agrega registro de usuario
  Frontend/pages/index.html
Labels: enhancement

#67 agrego estructura del login, registro a cada pagina
  Frontend/pages/about.html
  Frontend/pages/cart.html
  Frontend/pages/products.html
Labels: documentation, enhancement

#69 Reversión del merge a rama developer del pull request "agrego estructura del login, registro a cada pagina" para solucionar conflictos.
  Frontend/pages/about.html
  Frontend/pages/cart.html
  Frontend/pages/products.html
Labels: Improvement

#71 Pablo - agrega estructura de formulario de login
  Frontend/pages/about.html
  Frontend/pages/cart.html
  Frontend/pages/index.html
  Frontend/pages/products.html
Labels: Improvement, documentation

#68 Vicky
  Frontend/pages/about.html
  Frontend/pages/cart.html
  Frontend/pages/index.html
  Frontend/pages/products.html
Labels: help wanted

#72 Agrego instanciador de usuarios, gestor de usuarios, verificador de login y activador de logout
  Frontend/src/registerLoginForms/buildUserIntances.js
  Frontend/src/registerLoginForms/getUserInfo.js
  Frontend/src/registerLoginForms/handleLoginLogOutinterface.js
Labels: Improvement, enhancement

#73 Denisse - Agrega nuevo diseño para el footer, validaciones para el formulario de contacto y para el formulario de registro, y arreglos menores de html
  Frontend/pages/about.html
  Frontend/pages/cart.html
  Frontend/pages/index.html
  Frontend/pages/products.html
  Frontend/src/main.js
  Frontend/src/validadores/register.js
  Frontend/src/validadores/validator.js
Labels: Improvement, enhancement

#74 Cristian
  Frontend/src/main.js
  Frontend/src/themeModeToggler.js
Labels: Improvement, enhancement

#75 Subo archivos para completar la lógica del gestor de usuarios, corrijo detalles de posicionamiento del elementos HTML
  Frontend/pages/about.html
  Frontend/pages/cart.html
  Frontend/pages/index.html
  Frontend/pages/products.html
  Frontend/src/GestorDeUsuarios/buildUserIntances.js
  Frontend/src/GestorDeUsuarios/getUserInfo.js
  Frontend/src/GestorDeUsuarios/handleLoginLogOutinterface.js
  Frontend/src/GestorDeUsuarios/handleUsersLs.js
  Frontend/src/GestorDeUsuarios/passwordHider.js
  Frontend/src/GestorDeUsuarios/registerLoginUsers.js
  Frontend/src/main.js
Labels: Improvement, enhancement

#76 cambio la forma de validar los datos de registro de usuario.
  Frontend/pages/about.html
  Frontend/pages/cart.html
  Frontend/pages/index.html
  Frontend/pages/products.html
  Frontend/src/GestorDeUsuarios/registerLoginUsers.js
  Frontend/src/main.js
  Frontend/src/validadores/register.js
Labels: Improvement
